### ISSUE TITLE
can't add custom card

### ISSUE THREAD

**Issue by sezlony** [amaximus/radioactivity_hu#1]
reported error in script:

ButtonCardJSTemplateError: TypeError: states['sensor.radioactivity_hu'] is undefined in 'var r_val = states['sensor.radioactivity_hu'].state; if ( r_val > 500 ) { return "red"; } ...'

**Comment by amaximus** [comment]
Please make sure sensor.radioactivity_hu exists.

**Comment by sezlony** [comment]
should that be created by default or do I have to add it?

**Comment by amaximus** [comment]
It won't get created, so you'll have to add it as a sensor.

**Comment by amaximus** [comment]
Any updates on this?
Setting the card is just an example, it's out of scope for this repo.

**Comment by sezlony** [comment]
i gave up on this, i'm a newbie to HA and i'm not able to code anything (yet...)
i tried hard but it's outside my capabilities :D

however your help is highly appreciated!
