### ISSUE TITLE
Filter out inactive stations

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/radioactivity_hu#2]
The RAD.json has a field `active` for each station. This field is `true` only when the station has valid measurement data.

In this moment for example, station ID 103 has the `active` field set to `false`:
![kép](https://user-images.githubusercontent.com/1550668/166203136-ec034971-adab-46cb-a969-cc23d02275e1.png)
The station shows invalid meaurement data: the measured value is errorneously 329000 (and moreover, during the night it had a peak of 2.8 million) which means we all would be dead by now :D

This is important for the case when `station` parameter is not set in the configuration, the errorneous station with extreme values will always be shown as alerting.

Inactive stations are filtered out from the official webpage too (inactive stations are not shown in the list):
https://www.katasztrofavedelem.hu/modules/hattersugarzas/aktualis_adatsor

**Comment by amaximus** [comment]
THanks for reporting. I also saw Kecskemét with a very high value. Will fix it today.

**Comment by nagyrobi** [comment]
To improve accuracy, it's also worth filtering for `lastMeasurementTime`, there are stations with very old data (last measurement even from 2020(!), but quite a few from 2021 too) some of them still marked as active `true`.

Statistically:
- 2020 - 1 station
- 2021 - 9 stations
- 2022-02 - 6 stations
- 2022-03 - 1 station
- 2022-04 - 2 stations
- 2022-05 - 137 stations (less than 1,5 days passed from May)

So we could safely exclude from our list the stations which have `lastMeasurementTime` older than 24-36 hours, just to make sure the sensor won't show us too outdated info in case weather is so good that old data is higher...

**Comment by amaximus** [comment]
Version 0.2.0 addresses the issues above.

Please update your integration and get back to me with results.

**Comment by nagyrobi** [comment]
Perfect, thanks.
